# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e03bc68f8cab59990779c751c3296168a9db7e9a7799f6018e77c92457af542d4e3f8f7e8f0db7d45822da3e053ba81d44aa87f2b82fa4ab19f39c8af851f69

test:
  secret_key_base: 624f70eb5e5a778f758d2faf517ef03803169ddb168621d5d66f5d9f2163019ddd9ffa4adcb0076bb230f662b10c0814d24835f24096c92fdb6b71fead1e49f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
